[package]
name = "zkp_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
procfs = "0.14" # For system performance monitoring
